-- 1. write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
select order_no, purch_amt, order_date, customer_id , salesman_id 
from Orders where salesman_id = (select salesman_id from Salesman where name = 'Paul Adam');


-- 2.write a SQL query to find all the orders, which are generated by those salespeople, who live in the city of London.Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
select order_no, purch_amt, order_date, customer_id , salesman_id 
from Orders where salesman_id = (select salesman_id from Salesman where city = 'London');


-- 3. write a SQL query to find the orders generated by the salespeople who may work for customers whose id is 3007. Return ord_no, purch_amt, ord_date, customer_id, salesman_id
select order_no, purch_amt, order_date, customer_id , salesman_id 
from Orders where customer_id = 3007;


-- 4. write a SQL query to find the order values greater than the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id
select order_no, purch_amt, order_date, customer_id , salesman_id 
from Orders where purch_amt > (select avg(purch_amt) as 'Avg amount' from Orders group by order_date having order_date = '2012-10-10');


-- 5. write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
select order_no, purch_amt, order_date, customer_id , salesman_id 
from Orders where customer_id in (select customer_id from Customer where city = 'New York');


-- 6.write a SQL query to find the commission of the salespeople work in Paris City. Return commission.
select commission from Salesman where city = 'Paris' ;


-- 7.Write a query to display all the customers whose id is 2001 bellow the salesman ID of Mc Lyon
select * from Customer where customer_id = (select salesman_id -2001 from Salesman where name = 'Mc Lyon');


-- 8.write a SQL query to count number of customers with grades above the average grades of New York City. Return grade and count.
select grade, count(*) as 'Number of customers' from Customer where grade > (select avg(grade) as 'Avg grade' from Customer group by city having city = 'New York')
group by grade;




select * from Salesman;
select * from Customer;
select * from Orders;
